// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: 2026-08-21T06:13:43.302Z

export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface PostsRecord extends BaseRecord {
  "user_id": string;
  "content"?: string;
  "likes"?: number;
}

export interface AuthOriginsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "fingerprint": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface SuperusersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
}

export interface CommentsRecord extends BaseRecord {
  "text"?: string;
  "user_id"?: string;
  "post_id"?: string;
}

export interface MfasRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "method": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface ExternalAuthsRecord extends BaseRecord {
  "collection": string;
  "provider": string;
  "provider_id": string;
  "user_id": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface UsersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
  "name"?: string;
  "avatar"?: string;
  "verified": boolean;
  "verificationToken"?: string;
  "emailVisibility": boolean;
  "bio"?: string;
}

export interface OtpsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "sent_to"?: string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}

export interface LazypockCollections {
  "posts": PostsRecord;
  "_auth_origins": AuthOriginsRecord;
  "_superusers": SuperusersRecord & AuthRecord;
  "comments": CommentsRecord;
  "_mfas": MfasRecord;
  "_external_auths": ExternalAuthsRecord;
  "users": UsersRecord & AuthRecord;
  "_otps": OtpsRecord;
}

// Schema snapshot (runtime) — hidden-field exclusion + query validation.
export const lazypockSchema: import("lazypock").CollectionSchema[] = [
  {
    id: "f997e834-e608-4bac-a8b7-b6ea6e120c08",
    name: "posts",
    type: "base",
    system: false,
    fields: [
  {
    "hidden": false,
    "id": "c8976451-2bc6-41de-a0e2-57944d7202c5",
    "name": "user_id",
    "system": false,
    "type": "relation",
    "options": {
      "cascadeDelete": true,
      "collection": "users"
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": "eb101d79-4721-4753-8d4e-080b77d2ac9d"
  },
  {
    "hidden": false,
    "id": "a2344ae2-d0ec-4f11-9f21-36535f0eb70a",
    "name": "content",
    "system": false,
    "type": "editor",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "2cea9f1e-fdad-42b3-8381-f63204b4bd05",
    "name": "likes",
    "system": false,
    "type": "number",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  }
],
    rules: {"createRule":"@request.auth.id != ''","deleteRule":"","listRule":"","manageRule":null,"updateRule":"","viewRule":""},
    options: {"indexes":[]},
  },
  {
    id: "b5a06065-7cde-4ece-a772-fe3f870d931d",
    name: "_auth_origins",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "1a09a115-769b-4ccc-9226-4f0d843f97f2",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "d1ea83e0-a886-4320-a6c2-4067ded361d5",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "3d3b233e-eb6b-42a0-846a-a68d26ca8b82",
    "name": "fingerprint",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "181b78ca-a8e1-4dfb-ae0b-f1534cf22479",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "85cc154b-6328-4b01-953f-2bc3d94700f5",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "340c2e1e-c142-4148-9868-74e1722e044a",
    name: "_superusers",
    type: "auth",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "88d83416-2361-454f-932a-5d09fd25283b",
    "name": "email",
    "system": true,
    "type": "email",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "69e02b11-f56f-47c9-a8e8-7dc2a4911f75",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "7b4a8f07-9d96-436d-99b5-96d611e4e92f",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "70a27dc3-2657-457d-91a5-cd05800dfd01",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "820c83dd-07c5-47ac-aa85-a77d4427559e",
    name: "comments",
    type: "base",
    system: false,
    fields: [
  {
    "hidden": false,
    "id": "08713265-8c4f-4fe2-9cf1-f181daa09edc",
    "name": "text",
    "system": false,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "30ed90a8-872a-40ba-b96d-3c9a73baf1f0",
    "name": "user_id",
    "system": false,
    "type": "relation",
    "options": {
      "collection": "users"
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": "eb101d79-4721-4753-8d4e-080b77d2ac9d"
  },
  {
    "hidden": false,
    "id": "82ab7e2a-0021-4c64-93f4-ba65bab73901",
    "name": "post_id",
    "system": false,
    "type": "relation",
    "options": {
      "collection": "posts"
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": "f997e834-e608-4bac-a8b7-b6ea6e120c08"
  }
],
    rules: {"createRule":"@request.auth.id != ''","deleteRule":"","listRule":"","updateRule":"","viewRule":""},
    options: {"indexes":[]},
  },
  {
    id: "49ddf83a-5cd2-4d17-b56b-09db21446482",
    name: "_mfas",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "c76105cb-d589-42e2-972f-e684ab3f335d",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "02ea78f1-360a-4491-8e44-67da0562f3ca",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "05323884-51e1-40ba-b60f-cb72840118d4",
    "name": "method",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "3b21250e-b136-4eb0-83aa-0bb269a3aed6",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "6bacc01d-5ad6-44b5-8cc2-7b26b3dd3f46",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "590425c4-c524-4c65-b494-ce1dca6fed10",
    name: "_external_auths",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "8d86d0a4-544a-4984-8f48-d7841a408106",
    "name": "collection",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "abe4160f-c914-4ce1-899a-a6ac77fda36e",
    "name": "provider",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "a1b4708b-afde-4696-a692-b543bc17d5ab",
    "name": "provider_id",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "a4ced3f3-94fd-4487-900c-5f9fa2eea6c8",
    "name": "user_id",
    "system": true,
    "type": "relation",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "b6b73024-b623-4e4f-be3f-2d4e8caf2afb",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "c1305c5b-eae5-49b1-a24b-609901af2751",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "eb101d79-4721-4753-8d4e-080b77d2ac9d",
    name: "users",
    type: "auth",
    system: false,
    fields: [
  {
    "hidden": false,
    "id": "cba63e2f-0dd7-4aa8-8c27-244cbae2ed74",
    "name": "email",
    "system": true,
    "type": "email",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "5311ee28-381c-46fd-9f83-f563130d382c",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "b7ede923-35d0-465c-a401-f21ec7948914",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "d14af3e8-5828-4bdf-9542-ed7d767324dd",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "40d39bc2-fbb2-4413-b052-6a1e4252b8c4",
    "name": "name",
    "system": false,
    "type": "text",
    "options": {
      "max": 255
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "f584e61c-e441-4763-b121-e72c106685fb",
    "name": "avatar",
    "system": false,
    "type": "file",
    "options": {
      "maxSelect": 1,
      "mimeTypes": [
        "image/jpeg",
        "image/png",
        "image/svg+xml",
        "image/gif",
        "image/webp"
      ]
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "5dfeff78-5890-4908-8ccd-540f50bf4aa4",
    "name": "verified",
    "system": true,
    "type": "bool",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 6,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "9ee30e77-1499-454a-ac05-32e67275e9a6",
    "name": "verificationToken",
    "system": true,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 7,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "2717ce85-34e8-4b9f-8e98-c4dfa0a27c87",
    "name": "emailVisibility",
    "system": true,
    "type": "bool",
    "options": {
      "defaultValue": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 8,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "d7393bac-3907-4223-939e-914e4f9d6e52",
    "name": "bio",
    "system": false,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 9,
    "collectionId": null
  }
],
    rules: {"createRule":"","deleteRule":"id = @request.auth.id","listRule":"","updateRule":"id = @request.auth.id","viewRule":""},
    options: {"indexes":[]},
  },
  {
    id: "40e5f0cc-bd88-4cb8-8b8e-7eb3c11c1f7f",
    name: "_otps",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "454c068e-6438-4455-a4fa-d6943e3ebddf",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "b05d419e-ac7c-4cb0-a287-33288ac0c584",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "baff1eab-ff32-44d8-91ad-a18c46f413ac",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "d8342a03-4eaa-45ae-8508-6696080cea94",
    "name": "sent_to",
    "system": true,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "f826bc49-650b-4d7c-b4bc-a7094800ab7e",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "2ab6fd20-46e1-479e-8269-e1eeca168278",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  }
];

import { LazypockClient, type LazypockClientOptions, type CollectionService } from "lazypock";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 *
 * The schema snapshot is wired into the client automatically, so hidden
 * fields are excluded from responses and select/expand are validated.
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient({
    ...options,
    types: {
      ...options.types,
      schemas: options.types?.schemas ?? lazypockSchema,
    },
  });
}

export class TypedClient extends LazypockClient {
  override collection<T extends string>(name: T): T extends keyof LazypockCollections
    ? CollectionService<LazypockCollections[T]>
    : CollectionService<unknown> {
    return super.collection(name) as T extends keyof LazypockCollections ? CollectionService<LazypockCollections[T]> : CollectionService<unknown>;
  }
}

