// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: 2026-08-03T11:48:29.383Z

export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface ExternalAuthsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "provider": string;
  "provider_id": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface MfasRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "method": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface SuperusersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
}

export interface UsersRecord extends BaseRecord {
  "email": string;
  "name"?: string;
  "avatar"?: string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
  "verified": boolean;
  "verificationToken"?: string;
  "emailVisibility": boolean;
}

export interface PostsRecord extends BaseRecord {
  "text": string;
  "text2"?: string;
  "date"?: string;
  "relation"?: string;
  "select"?: "Value 1" | "Value 2";
  "cate"?: string;
}

export interface CateRecord extends BaseRecord {
  "title"?: string;
}

export interface OtpsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "sent_to"?: string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface AccountsRecord extends BaseRecord {
  "name"?: string;
  "email": string;
}

export interface AuthOriginsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "fingerprint": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}

export interface LazypockCollections {
  "_external_auths": ExternalAuthsRecord;
  "_mfas": MfasRecord;
  "_superusers": SuperusersRecord & AuthRecord;
  "users": UsersRecord & AuthRecord;
  "posts": PostsRecord;
  "cate": CateRecord;
  "_otps": OtpsRecord;
  "accounts": AccountsRecord & AuthRecord;
  "_auth_origins": AuthOriginsRecord;
}

import { LazypockClient, type LazypockClientOptions, type CollectionService } from "lazypock";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient(options);
}

export class TypedClient extends LazypockClient {
  override collection<K extends keyof LazypockCollections>(name: K): CollectionService<LazypockCollections[K]>;
  override collection(name: string): CollectionService<unknown> {
    return super.collection(name) as unknown as CollectionService<unknown>;
  }
}
