// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: 2026-08-21T11:27:48.700Z

export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface ExternalAuthsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "provider": string;
  "provider_id": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface MfasRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "method": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface SuperusersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
}

export interface UsersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
  "name"?: string;
  "avatar"?: string;
  "verified": boolean;
  "verificationToken"?: string;
  "emailVisibility": boolean;
}

export interface PostsRecord extends BaseRecord {}

export interface OtpsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "sent_to"?: string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface AuthOriginsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "fingerprint": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}

export interface LazypockCollections {
  "_external_auths": ExternalAuthsRecord;
  "_mfas": MfasRecord;
  "_superusers": SuperusersRecord & AuthRecord;
  "users": UsersRecord & AuthRecord;
  "posts": PostsRecord;
  "_otps": OtpsRecord;
  "_auth_origins": AuthOriginsRecord;
}

// Schema snapshot (runtime) — hidden-field exclusion + query validation.
export const lazypockSchema: import("lazypock").CollectionSchema[] = [
  {
    id: "838c29af-006a-4927-8418-e6fc7c247237",
    name: "_external_auths",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "6a9d0e5d-3e4e-4f23-ab46-6e8151ff3817",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "b92565f1-5645-41df-a59b-d2be33db059d",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "8705a369-00fb-4894-94a1-1f21020dbb8e",
    "name": "provider",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "8d681f47-6e75-4a8b-bd2e-3dd8be8e2fb4",
    "name": "provider_id",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "f2208443-e380-40f2-8902-4d47ffe4fd68",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "e34ab49b-a688-4e8a-ab9b-0a2bc65d7966",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "57c8b64f-ed05-48d8-95bc-21985c18e3e6",
    name: "_mfas",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "d8b84ba7-011d-4d45-84c2-d8ab21fbc567",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "e6abfdb0-413a-4c78-917d-36702e065e6b",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "edc0e2a6-3b41-4c50-a6e2-a177c0c9f056",
    "name": "method",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "10cb410c-e5f8-4b8a-87b3-e86191f67d46",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "77141cda-c403-4375-bc80-ee1e9583f9b5",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "4f51b16e-da9e-4bf6-a195-58a29540d880",
    name: "_superusers",
    type: "auth",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "8be91d80-9f11-468b-bc4a-e420f1eacb3e",
    "name": "email",
    "system": true,
    "type": "email",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "516d15e0-2af0-411c-9a11-6a9e3f3b6682",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "25278089-a787-4b4c-b0ed-c1ee49e4e4e7",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "e43d020d-6ff4-46bf-8980-2200eb5604d8",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "ef17e91a-900d-4524-afa9-81699f5c0e6d",
    name: "users",
    type: "auth",
    system: false,
    fields: [
  {
    "hidden": false,
    "id": "9130f397-93c0-4818-8b25-5998356e4c4b",
    "name": "email",
    "system": true,
    "type": "email",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "04952e82-eeb7-4a16-ba00-5b08a889d43d",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "7ab8e31e-10f4-4bcc-abf7-857540effb69",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "c25df3ba-5b55-4f44-bbf4-4f10e4b23a60",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "2c36140d-663c-4578-a962-0b497fae417c",
    "name": "name",
    "system": false,
    "type": "text",
    "options": {
      "max": 255
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "5bdf0ff4-e882-4f5f-a20c-8ffe66c0224f",
    "name": "avatar",
    "system": false,
    "type": "file",
    "options": {
      "maxSelect": 1,
      "mimeTypes": [
        "image/jpeg",
        "image/png",
        "image/svg+xml",
        "image/gif",
        "image/webp"
      ]
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "74141ae3-0206-461a-acef-12e2e4ee08ee",
    "name": "verified",
    "system": true,
    "type": "bool",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 6,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "a66e7b05-982e-4d95-a1ac-7ea62e1e81e8",
    "name": "verificationToken",
    "system": true,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 7,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "60ad1673-8db5-4f94-a450-5238fcf0a051",
    "name": "emailVisibility",
    "system": true,
    "type": "bool",
    "options": {
      "defaultValue": true
    },
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 8,
    "collectionId": null
  }
],
    rules: {"createRule":"","deleteRule":"id = @request.auth.id","listRule":"","updateRule":"id = @request.auth.id","viewRule":""},
    options: {},
  },
  {
    id: "39c5bcc4-a140-4c50-b946-b523fb96da3f",
    name: "posts",
    type: "base",
    system: false,
    fields: [],
    rules: {},
    options: {},
  },
  {
    id: "2f823ae9-dc48-45ab-9fbc-efa4eacac97d",
    name: "_otps",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "2f94074b-fb9c-4a27-a4a9-265f8e906d04",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "17b6d0f3-737b-4fd0-86c0-1ea8ff340791",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "62f90243-ecd9-4189-9c7a-189ac6228ac7",
    "name": "password_hash",
    "system": true,
    "type": "password",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "641274c0-58b1-41aa-b0d6-e2baba0c42d1",
    "name": "sent_to",
    "system": true,
    "type": "text",
    "options": {},
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "a6492451-0b87-4b07-872c-f12e652d3c5a",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "ef807b41-f6d8-477c-abd4-14d82c18ddb6",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 5,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  },
  {
    id: "c3c1d208-29a7-41bd-8179-962f8bc682a3",
    name: "_auth_origins",
    type: "base",
    system: true,
    fields: [
  {
    "hidden": false,
    "id": "75414f7f-0a8c-4aa3-a1a9-1143aa9c5fb0",
    "name": "collection_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 0,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "4b5a1be4-7044-4534-b489-f442541f9563",
    "name": "record_ref",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 1,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "446373bc-981e-46e3-a94a-8e94b0a9c5b4",
    "name": "fingerprint",
    "system": true,
    "type": "text",
    "options": {},
    "required": true,
    "unique": false,
    "indexed": false,
    "sort_order": 2,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "76aa5fc7-d040-42d4-a7b1-f2a38d215d3a",
    "name": "created_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 3,
    "collectionId": null
  },
  {
    "hidden": false,
    "id": "797746a1-f678-4a2d-81fb-259e6ad22ed2",
    "name": "updated_at",
    "system": true,
    "type": "autodate",
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "required": false,
    "unique": false,
    "indexed": false,
    "sort_order": 4,
    "collectionId": null
  }
],
    rules: {},
    options: {},
  }
];

import { LazypockClient, type LazypockClientOptions, type CollectionService } from "lazypock";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 *
 * The schema snapshot is wired into the client automatically, so hidden
 * fields are excluded from responses and select/expand are validated.
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient({
    ...options,
    types: {
      ...options.types,
      schemas: options.types?.schemas ?? lazypockSchema,
    },
  });
}

export class TypedClient extends LazypockClient {
  override collection<T extends string>(name: T): T extends keyof LazypockCollections
    ? CollectionService<LazypockCollections[T]>
    : CollectionService<unknown> {
    return super.collection(name) as T extends keyof LazypockCollections ? CollectionService<LazypockCollections[T]> : CollectionService<unknown>;
  }
}

