// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: 2026-08-16T12:45:52.777Z

export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface AuthOriginsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "fingerprint": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface ExternalAuthsRecord extends BaseRecord {
  "collection": string;
  "provider": string;
  "provider_id": string;
  "user_id": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface MfasRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "method": string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface OtpsRecord extends BaseRecord {
  "collection_ref": string;
  "record_ref": string;
  "sent_to"?: string;
  "created_at"?: unknown;
  "updated_at"?: unknown;
}

export interface SuperusersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
}

export interface PostsRecord extends BaseRecord {}

export interface UsersRecord extends BaseRecord {
  "email": string;
  "created_at": unknown;
  "updated_at": unknown;
  "name"?: string;
  "avatar"?: string;
  "verified": boolean;
  "verificationToken"?: string;
  "emailVisibility": boolean;
}

export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}

export interface LazypockCollections {
  "_auth_origins": AuthOriginsRecord;
  "_external_auths": ExternalAuthsRecord;
  "_mfas": MfasRecord;
  "_otps": OtpsRecord;
  "_superusers": SuperusersRecord & AuthRecord;
  "posts": PostsRecord;
  "users": UsersRecord & AuthRecord;
}

// Schema snapshot (runtime) — hidden-field exclusion + query validation.
export const lazypockSchema: import("lazypock").CollectionSchema[] = [
  {
    id: "5dd2f14f-95f8-4a94-bcda-6fc5e5db60cc",
    name: "_auth_origins",
    type: "base",
    system: true,
    fields: [
  {
    "name": "collection_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "record_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "fingerprint",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 2
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 3
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 4
  }
],
    rules: {},
    options: {},
  },
  {
    id: "5e28ca86-8f94-48bb-a8f2-15af47e00ddf",
    name: "_external_auths",
    type: "base",
    system: true,
    fields: [
  {
    "name": "collection",
    "type": "text",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "provider",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "provider_id",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 2
  },
  {
    "name": "user_id",
    "type": "relation",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 3
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 4
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 5
  }
],
    rules: {},
    options: {},
  },
  {
    id: "175efc71-12c6-4df8-a983-749cfc2a284d",
    name: "_mfas",
    type: "base",
    system: true,
    fields: [
  {
    "name": "collection_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "record_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "method",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 2
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 3
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 4
  }
],
    rules: {},
    options: {},
  },
  {
    id: "200d29dd-aaa2-429a-b6d4-22991e2815b4",
    name: "_otps",
    type: "base",
    system: true,
    fields: [
  {
    "name": "collection_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "record_ref",
    "type": "text",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "password_hash",
    "type": "password",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 2
  },
  {
    "name": "sent_to",
    "type": "text",
    "required": false,
    "options": {},
    "system": true,
    "sort_order": 3
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 4
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": false,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 5
  }
],
    rules: {},
    options: {},
  },
  {
    id: "f33f5fa5-c065-4c57-9b55-ab9beb36ad1f",
    name: "_superusers",
    type: "auth",
    system: true,
    fields: [
  {
    "name": "email",
    "type": "email",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "password_hash",
    "type": "password",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": true,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 2
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": true,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 3
  }
],
    rules: {},
    options: {},
  },
  {
    id: "5f2f1fd6-c892-4393-ba51-5ab39075a401",
    name: "posts",
    type: "base",
    system: false,
    fields: [],
    rules: {},
    options: {},
  },
  {
    id: "8843aef1-327b-4ec1-af55-67b5fc8bec1c",
    name: "users",
    type: "auth",
    system: false,
    fields: [
  {
    "name": "email",
    "type": "email",
    "required": true,
    "options": {},
    "system": true
  },
  {
    "name": "password_hash",
    "type": "password",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 1
  },
  {
    "name": "created_at",
    "type": "autodate",
    "required": true,
    "options": {
      "onCreate": true
    },
    "system": true,
    "sort_order": 2
  },
  {
    "name": "updated_at",
    "type": "autodate",
    "required": true,
    "options": {
      "onCreate": true,
      "onUpdate": true
    },
    "system": true,
    "sort_order": 3
  },
  {
    "name": "name",
    "type": "text",
    "required": false,
    "options": {
      "max": 255
    },
    "sort_order": 4
  },
  {
    "name": "avatar",
    "type": "file",
    "required": false,
    "options": {
      "maxSelect": 1,
      "mimeTypes": [
        "image/jpeg",
        "image/png",
        "image/svg+xml",
        "image/gif",
        "image/webp"
      ]
    },
    "sort_order": 5
  },
  {
    "name": "verified",
    "type": "bool",
    "required": true,
    "options": {},
    "system": true,
    "sort_order": 6
  },
  {
    "name": "verificationToken",
    "type": "text",
    "required": false,
    "options": {},
    "system": true,
    "sort_order": 7
  },
  {
    "name": "emailVisibility",
    "type": "bool",
    "required": true,
    "options": {
      "defaultValue": true
    },
    "system": true,
    "sort_order": 8
  }
],
    rules: {"listRule":"","viewRule":"","createRule":"","deleteRule":"id = @request.auth.id","updateRule":"id = @request.auth.id"},
    options: {},
  }
];

import { LazypockClient, type LazypockClientOptions, type CollectionService } from "lazypock";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 *
 * The schema snapshot is wired into the client automatically, so hidden
 * fields are excluded from responses and select/expand are validated.
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient({
    ...options,
    types: {
      ...options.types,
      schemas: options.types?.schemas ?? lazypockSchema,
    },
  });
}

export class TypedClient extends LazypockClient {
  override collection<T extends string>(name: T): T extends keyof LazypockCollections
    ? CollectionService<LazypockCollections[T]>
    : CollectionService<unknown> {
    return super.collection(name) as T extends keyof LazypockCollections ? CollectionService<LazypockCollections[T]> : CollectionService<unknown>;
  }
}

