// AUTO-GENERATED by scripts/sync-sdks.mjs — do not edit.
// Regenerated on every build; reflects the <h2> sections of each SDK page.

export interface SdkPage {
	slug: string;
	label: string;
}

export interface SdkNavEntry {
	slug: string;
	name: string;
	pages: SdkPage[];
}

export const sdkNav: SdkNavEntry[] = [
	{
		"slug": "typescript",
		"name": "TypeScript",
		"pages": [
			{
				"slug": "install",
				"label": "Install"
			},
			{
				"slug": "quick-start",
				"label": "Quick Start"
			},
			{
				"slug": "type-safety",
				"label": "Type Safety"
			},
			{
				"slug": "queries",
				"label": "Queries"
			},
			{
				"slug": "realtime",
				"label": "Realtime"
			},
			{
				"slug": "files",
				"label": "Files"
			},
			{
				"slug": "auth",
				"label": "Auth"
			},
			{
				"slug": "api-reference",
				"label": "API Reference"
			}
		]
	}
];
